apiVersion: batch/v1
kind: Job
metadata:
  name: pi-pod

spec:
 template:
   spec:
    containers:
    - name: container-pi
      image: perl
      command: ["perl", "-Mbignum=bpi", "-wle", "print bpi(2000)"]
    reatartPolicy: Never