# CREATE CLUSTER IP

apiVersion: v1 #versao da API
kind: Service  #tipo
metadata:
   name: svc-pod-2
spec:
  type: ClusterIP #tipo de service 
  ports:
    - port: 80

  selector:
    app: segundo-pod # junto com "selector" seleciona o pod, exemplo: aqui estamos selecionando o (pod-2.yaml)   
      
      

