apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-noticias-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-noticias
  template:
    metadata:
      labels:
        app: db-noticias
    spec:
      containers:
        - name: db-noticias-container
          image: aluracursos/portal-noticias:1
